const gigs = [
    {
      id: 1,
      title: "Custom Bridal Gown Tailoring",
      description: "Expert in designing and stitching bridal gowns with lace and satin materials.",
      image: "images/fitting preview.png",
      price: 15000,
      catergory: "tailoring",
      username:"John Doe",
      user_img:"images/fitting preview.png",
      star:4,
    },
    {
      id: 2,
      title: "Modern Men's Suit Designer",
      description: "Specializing in slim-fit and traditional men’s suits for weddings and business events.",
      image: "https://example.com/suit-designer.jpg",
      price: 10000,
      catergory: "design",
      username:"Jane Smith",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:5,
    },
    {
      id: 3,
      title: "Kids Wear Specialist",
      description: "Comfortable and creative outfits for kids. Available in all sizes.",
      image: "https://example.com/kids-tailor.jpg",
      price: 5000,
      catergory: "design",
      username:"Alice Brown",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:4,
    },
    {
      id: 4,
      title: "Alteration Services",
      description: "Expert in altering dresses, suits, and other garments to fit perfectly.",
      image: "https://example.com/alteration-services.jpg",
      price: 2000,
      catergory: "tailoring",
      username:"Bob Johnson",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:3,
    },
    {
      id: 5,
      title: "Custom T-Shirt Printing",
      description: "Design and print custom t-shirts for events, teams, or personal use.",
      image: "https://example.com/tshirt-printing.jpg",
      price: 1500,
      catergory: "design",
      username:"Charlie Davis",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:4,
    },
    {
      id: 6,
      title: "Fashion Design Consultation",
      description: "Personalized fashion design consultations to help you create your unique style.",
      image: "https://example.com/fashion-consultation.jpg",
      price: 8000,
      catergory: "design",
      username:"David Wilson",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:5,
    },
    {
      id: 7,
      title: "Saree Draping and Tailoring",
      description: "Expert in saree draping and tailoring for traditional occasions.",      
      image: "https://example.com/saree-draping.jpg",
      price: 6000,
      catergory: "tailoring",
      username:"Eva Martinez",
      user_img:"https://images.unsplash.com/photo-1502685104226-e9df14d4d9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      star:4,
    },
  ];
  
  export default gigs;
  